const STORAGE_KEY='autorozsudek-kontrola-v1';
const STATUS=[['V POŘÁDKU','ok'],['VÝHRADA','warn'],['ZÁVADA / RIZIKO','bad'],['NEOVĚŘENO','unknown'],['NERELEVANTNÍ','na']];
const navItems=[['vehicle','Vozidlo a zakázka'],['photos','Fotografie vozu'],['body','Karoserie, světla, skla a lak'],['wheels','Kola a pneumatiky'],['brakes','Brzdy'],['engine','Motor a převodovka'],['underbody','Podvozek, nápravy a řízení'],['interior','Interiér a výbava'],['documents','Identifikace, dokumentace a historie'],['diagnostics','Diagnostika'],['drive','Zkušební jízda'],['investments','Servis a investice'],['final','Finální rozsudek']];
let state=load();
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return {}}}
function get(path){return path.split('.').reduce((o,k)=>o?.[k],state)}
function set(path,value){const keys=path.split('.');let o=state;keys.slice(0,-1).forEach(k=>o=o[k]??={});o[keys.at(-1)]=value;save();updateInvestmentTotal()}
let saveTimer;function save(){const s=document.querySelector('#saveState');if(s)s.textContent='Ukládám…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(s)s.textContent='Uloženo v zařízení'},180)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function status(path){return `<div class="status-row" data-choice="${path}">${STATUS.map(([v,c])=>`<button type="button" class="${c}" data-value="${v}">${v}</button>`).join('')}</div>`}
function note(path,placeholder='Konkrétní zjištění…'){return `<label>Poznámka / diktování<textarea data-field="${path}" rows="2" placeholder="${placeholder}"></textarea></label>`}
function point(key,title,extra=''){return `<div class="check-point"><h3>${title}</h3>${status(`sections.${key}.status`)}${extra}${note(`sections.${key}.note`)}</div>`}
function nav(){document.querySelector('#sectionNav').innerHTML=navItems.map((x,i)=>`<a href="#${x[0]}"><span class="nav-num">${String(i+1).padStart(2,'0')}</span>${x[1]}</a>`).join('')}
function card(id,num,title,body,tag=''){return `<section class="card" id="${id}"><div class="section-heading"><div><span class="step">${num}</span><h2>${title}</h2></div>${tag?`<span class="optional">${tag}</span>`:''}</div>${body}</section>`}
function bodySection(){const parts=['Přední nárazník','Kapota','LP blatník','LP dveře','LZ dveře','Levý zadní bok','Víko kufru','Pravý zadní bok','PZ dveře','PP dveře','PP blatník','Zadní nárazník'];return card('body','03','Karoserie, světla, skla a lak',`<div class="subhead"><b>03A · Vizuální stav karoserie, světel a skel</b><span>Vizuální stav a funkce</span></div>${point('body.visual','Karoserie')}${point('body.lights','Světla')}${point('body.glass','Skla')}<div class="subhead paint"><b>03B · Měření tloušťky laku</b><span>Zapisuje se nejvyšší naměřená hodnota, nikdy průměr</span></div><div class="paint-grid">${parts.map((p,i)=>`<div class="paint-part"><b>${i+1}. ${p}</b><div class="paint-fields"><label>MAX µm<input data-field="paint.${i}.um" inputmode="numeric" placeholder="—"></label><label>Vyhodnocení<select data-field="paint.${i}.result"><option value="">Vyberte…</option><option>Původní / bez podezření</option><option>Lakováno</option><option>Podezření na větší opravu</option><option>PLAST</option><option>Nelze změřit</option></select></label></div>${note(`paint.${i}.note`,'Volitelné…')}</div>`).join('')}</div>`)}
function wheels(){return card('wheels','04','Kola a pneumatiky',`<p class="muted">Model pneumatiky ani rozměr/ET disku se rutinně nezapisují. Disk se hodnotí vizuálně.</p><div class="wheel-grid">${['LP','PP','LZ','PZ'].map(pos=>`<div class="wheel"><div class="wheel-icon">◉</div><h3>${pos}</h3><label>Rozměr pneumatiky<input data-field="wheels.${pos}.size" placeholder="215/55 R17"></label><div class="grid cols-2"><label>DOT<input data-field="wheels.${pos}.dot" placeholder="2524"></label><label>Dezén mm<input data-field="wheels.${pos}.tread" inputmode="decimal" placeholder="5,4"></label></div>${status(`wheels.${pos}.status`)}${note(`wheels.${pos}.note`,'Pneumatika / disk – pouze relevantní nález…')}</div>`).join('')}</div>`)}
function brakes(){return card('brakes','05','Brzdy',`<p class="muted">Statická kontrola = pouze to, co je skutečně vidět. Funkční chování brzd patří do zkušební jízdy.</p><div class="wheel-grid">${['LP','PP','LZ','PZ'].map(pos=>`<div class="wheel"><div class="brake-icon">◎</div><h3>${pos}</h3>${status(`brakes.${pos}.status`)}${note(`brakes.${pos}.note`,'Kotouč, destičky; třmen pouze viditelná abnormalita…')}</div>`).join('')}</div>${point('brakes.fluid','Brzdová kapalina – hladina a vizuální stav')}`)}
function engine(){return card('engine','06','Motorový prostor, motor a převodovka',`<div class="grid cols-2"><label>Teplota motoru při příjezdu<select data-field="engine.arrivalTemp"><option value="">Vyberte…</option><option>Studený</option><option>Částečně zahřátý</option><option>Zahřátý</option></select></label><label>Studený start<select data-field="engine.coldStart"><option value="">Vyberte…</option><option>Ověřen</option><option>Neověřen</option></select></label></div>${point('engine.bay','Motorový prostor – vizuální stav')}${point('engine.fluids','Provozní kapaliny')}${point('engine.start','Start a chod motoru')}${point('engine.warm','Kontrola po zahřátí')}${point('engine.gearboxVisual','Převodovka – viditelný fyzický stav')}`)}
function underbody(){return card('underbody','07','Podvozek, nápravy a řízení',`<label>Způsob kontroly<select data-field="underbody.method"><option value="">Vyberte…</option><option>Ze země</option><option>Částečně přizvednuto</option><option>Jiný způsob</option></select></label>${point('underbody.front','Přední náprava')}${point('underbody.rear','Zadní náprava')}${point('underbody.steering','Řízení – statická kontrola')}${point('underbody.floor','Spodek vozidla')}${point('underbody.exhaust','Výfuková soustava')}${point('underbody.drive','Pohon / AWD dle vozidla')}${point('underbody.special','Specifické systémy dle výbavy')}<label class="checkline"><input type="checkbox" data-field="underbody.verifyDrive"> Přenést nález k ověření při zkušební jízdě</label>`)}
function interior(){return card('interior','08','Interiér a výbava',`<div class="subhead"><b>08A · Vizuální stav interiéru</b></div>${point('interior.visual','Interiér – vizuální stav')}<div class="subhead"><b>08B · Funkčnost výbavy a ovládání</b></div>${point('interior.windows','Okna, zrcátka a centrální zamykání')}${point('interior.controls','Světla, stěrače a základní ovládání')}${point('interior.info','Infotainment / rádio / konektivita')}${point('interior.climate','Klimatizace a ventilace')}${point('interior.cluster','Přístrojový štít / displeje')}<label class="checkline"><input type="checkbox" data-field="interior.allPresentOk"> Otestoval jsem přítomné ovládací prvky a nezjistil závadu.</label><label>Další výbava vozidla<textarea data-field="interior.extra" rows="3" placeholder="Pouze skutečně přítomná výbava – panorama, kamera, HUD, elektrické víko…"></textarea></label>`)}
function documents(){return card('documents','09','Identifikace, dokumentace a servisní historie',`<div class="subhead"><b>09A · Identifikace vozidla a soulad s doklady</b></div>${point('documents.identity','VIN a identifikátory')}${point('documents.compliance','Soulad vozidla s technickými doklady')}<div class="subhead"><b>09B · Technické údaje a schválené změny</b></div>${point('documents.tech','Relevantní technické údaje / registrované úpravy')}<div class="subhead"><b>09C · Servisní historie a dokumentace</b></div><label>Stav doložení<select data-field="documents.history"><option value="">Vyberte…</option><option>Doložená</option><option>Částečně doložená</option><option>Nedoložená</option><option>Nebyla předložena</option></select></label>${note('documents.events','Významné doložené servisní události – datum/km, pokud jsou známy…')}`)}
function diagnostics(){return card('diagnostics','10','Diagnostika',`<div class="grid cols-3"><label>Diagnostika<select data-field="diagnostics.done"><option value="">Vyberte…</option><option>Provedena</option><option>Neprovedena</option></select></label><label>Řídicí jednotky<input data-field="diagnostics.units" inputmode="numeric"></label><label>Počet závad<input data-field="diagnostics.faults" inputmode="numeric"></label></div><div class="grid cols-2"><label>Aktivní závady<input data-field="diagnostics.active" inputmode="numeric"></label><label>Historické / sporadické<input data-field="diagnostics.history" inputmode="numeric"></label></div>${note('diagnostics.note','Významné diagnostické nálezy a komentář technika…')}<label class="upload-box small"><input id="diagInput" type="file" multiple><strong>+ Přidat diagnostický protokol / soubor</strong><span>Více souborů; originální protokol zůstává přílohou</span></label><div id="diagList" class="photo-list"></div>`)}
function drive(){const items=[['motor','Motor'],['gearbox','Převodovka / spojka'],['suspension','Podvozek'],['brakes','Brzdy + parkovací brzda'],['steering','Řízení'],['acceleration','Akcelerace'],['assist','Asistenční systémy']];return card('drive','11','Zkušební jízda',`<div class="safety-note"><b>Zjištění zapisujte až po zastavení vozidla.</b> Fotografie ani video během řízení aplikace nevyžaduje.</div><div id="driveReminder"></div>${items.map(([k,t])=>point(`drive.${k}`,t)).join('')}`)}
function investments(){return card('investments','12','Doporučený servis a očekávané investice',`<p class="muted">Na konci se sem přenesou nalezené problémy. Technik rozhoduje, co zařadit, a zadává vlastní odhad ceny. Systém pouze sčítá.</p><div id="investmentRows"></div><button type="button" class="ghost" id="addInvestment">+ Přidat položku</button><div class="total-box"><span>ODHADOVANÉ INVESTICE</span><strong id="investmentTotal">0 – 0 Kč</strong></div>`)}
function render(){nav();document.querySelector('#dynamicSections').innerHTML=[bodySection(),wheels(),brakes(),engine(),underbody(),interior(),documents(),diagnostics(),drive(),investments()].join('');renderInvestments();bind();restore();renderReminder();document.querySelector('#inspectionId').textContent=state.meta?.id||makeId();renderFiles()}
function makeId(){const id=`AR-${new Date().getFullYear()}-00001`;set('meta.id',id);return id}
function bind(){document.querySelectorAll('[data-field]').forEach(el=>{const path=el.dataset.field;if(el.type==='checkbox'){el.checked=!!get(path);el.addEventListener('change',()=>set(path,el.checked))}else{el.value=get(path)??'';el.addEventListener('input',()=>set(path,el.value));el.addEventListener('change',()=>set(path,el.value))}});document.querySelectorAll('[data-choice] button').forEach(btn=>btn.onclick=()=>{const row=btn.closest('[data-choice]');set(row.dataset.choice,btn.dataset.value);row.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===btn))});document.querySelectorAll('.verdict-picker button').forEach(btn=>btn.onclick=()=>{set('final.verdict',btn.dataset.value);restore()});const add=document.querySelector('#addInvestment');if(add)add.onclick=()=>{const a=get('investments.items')||[];a.push({title:'',min:'',max:'',priority:'',include:true});set('investments.items',a);renderInvestments();bind();restore()};const d=document.querySelector('#diagInput');if(d)d.onchange=e=>{set('diagnostics.files',[...e.target.files].map(f=>f.name));renderFiles()}}
function restore(){document.querySelectorAll('[data-choice]').forEach(row=>{const v=get(row.dataset.choice);row.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.value===v))});const v=get('final.verdict');document.querySelectorAll('.verdict-picker button').forEach(b=>b.classList.toggle('active',b.dataset.value===v))}
function renderReminder(){const el=document.querySelector('#driveReminder');if(!el)return;el.innerHTML=get('underbody.verifyDrive')?`<div class="reminder"><b>K OVĚŘENÍ BĚHEM JÍZDY</b><span>${esc(get('sections.underbody.note')||'Nález z předchozí kontroly podvozku / řízení.')}</span></div>`:''}
function renderInvestments(){const el=document.querySelector('#investmentRows');if(!el)return;const a=get('investments.items')||[];el.innerHTML=a.map((x,i)=>`<div class="investment-row"><label class="checkline"><input type="checkbox" data-field="investments.items.${i}.include" ${x.include!==false?'checked':''}> Zařadit do očekávaných investic</label><label>Nález / servis<input data-field="investments.items.${i}.title" value="${esc(x.title)}" placeholder="Např. přední kotouče + destičky"></label><div class="grid cols-3"><label>Minimum Kč<input data-field="investments.items.${i}.min" value="${esc(x.min)}" inputmode="numeric"></label><label>Maximum Kč<input data-field="investments.items.${i}.max" value="${esc(x.max)}" inputmode="numeric"></label><label>Priorita<select data-field="investments.items.${i}.priority"><option value="">Vyberte…</option><option ${x.priority==='Co nejdříve'?'selected':''}>Co nejdříve</option><option ${x.priority==='Doporučeno řešit'?'selected':''}>Doporučeno řešit</option><option ${x.priority==='Dle uvážení'?'selected':''}>Dle uvážení</option></select></label></div><button type="button" class="remove-investment" data-i="${i}">Odstranit</button></div>`).join('');el.querySelectorAll('.remove-investment').forEach(b=>b.onclick=()=>{const a=get('investments.items')||[];a.splice(+b.dataset.i,1);set('investments.items',a);renderInvestments();bind();restore()});updateInvestmentTotal()}
function money(v){return Number(String(v||'').replace(/\D/g,''))||0}function updateInvestmentTotal(){const a=get('investments.items')||[];let min=0,max=0;a.filter(x=>x.include!==false).forEach(x=>{min+=money(x.min);max+=money(x.max)});const el=document.querySelector('#investmentTotal');if(el)el.textContent=`${min.toLocaleString('cs-CZ')} – ${max.toLocaleString('cs-CZ')} Kč`;const f=document.querySelector('#finalInvestmentTotal');if(f)f.textContent=`${min.toLocaleString('cs-CZ')} – ${max.toLocaleString('cs-CZ')} Kč`}
function renderFiles(){const photos=get('photos.names')||[];const p=document.querySelector('#photoList');if(p)p.innerHTML=photos.map(n=>`<span class="photo-pill">${esc(n)}</span>`).join('');const files=get('diagnostics.files')||[];const d=document.querySelector('#diagList');if(d)d.innerHTML=files.map(n=>`<span class="photo-pill">${esc(n)}</span>`).join('')}
document.querySelector('#photoInput').addEventListener('change',e=>{const names=[...e.target.files].map(f=>f.name);set('photos.names',names);renderFiles()});document.querySelector('#resetBtn').addEventListener('click',()=>{if(confirm('Opravdu vymazat celý lokálně uložený koncept této kontroly?')){localStorage.removeItem(STORAGE_KEY);location.reload()}});
render();