const STORAGE_KEY='autorozsudek-kontrola-v1';
const STATUS=[['V POŘÁDKU','ok'],['VÝHRADA','warn'],['ZÁVADA / RIZIKO','bad'],['NEOVĚŘENO','unknown'],['NERELEVANTNÍ','na']];
const navItems=[['vehicle','Vozidlo a zakázka'],['photos','Fotografie vozu'],['body','Karoserie, světla, skla a lak'],['wheels','Kola a pneumatiky'],['brakes','Brzdy'],['engine','Motorový prostor, motor a převodovka'],['underbody','Podvozek a nápravy'],['interior','Interiér a výbava'],['documents','Identifikace, dokumentace a servisní historie'],['diagnostics','Diagnostika'],['drive','Zkušební jízda'],['investments','Doporučený servis a očekávané investice'],['final','Finální rozsudek']];
let state=load();
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return {}}}
function get(p){return p.split('.').reduce((o,k)=>o?.[k],state)}
function set(p,v){const k=p.split('.');let o=state;k.slice(0,-1).forEach(x=>o=o[x]??={});o[k.at(-1)]=v;save();updateInvestmentTotal()}
let saveTimer;
function save(){const s=document.querySelector('#saveState');if(s)s.textContent='Ukládám…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(s)s.textContent='Uloženo v zařízení'},180)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function status(path,allowNA=true){const opts=allowNA?STATUS:STATUS.filter(x=>x[0]!=='NERELEVANTNÍ');return '<div class="status-row" data-choice="'+path+'">'+opts.map(([v,c])=>'<button type="button" class="'+c+'" data-value="'+v+'">'+v+'</button>').join('')+'</div>'}
function note(path,ph='Konkrétní zjištění…'){return '<label>Poznámka / diktování<textarea data-field="'+path+'" rows="2" placeholder="'+ph+'"></textarea></label>'}
function media(path,label='＋ Přidat foto'){return '<div class="finding-media"><label class="mini-upload"><input type="file" accept="image/*,video/*" multiple data-media="'+path+'"><span>'+label+'</span></label><div class="media-files" data-media-list="'+path+'"></div></div>'}
function point(key,title,extra='',withMedia=true){return '<div class="check-point"><h3>'+title+'</h3>'+status('sections.'+key+'.status')+extra+note('sections.'+key+'.note')+(withMedia?media('sections.'+key+'.photos'):'')+'</div>'}
function nav(){document.querySelector('#sectionNav').innerHTML=navItems.map((x,i)=>'<a href="#'+x[0]+'"><span class="nav-num">'+(i+1)+'</span>'+x[1]+'</a>').join('')}
function card(id,num,title,body){return '<section class="card" id="'+id+'"><div class="section-heading"><div><span class="step">'+num+'</span><h2>'+title+'</h2></div></div>'+body+'</section>'}

function bodyMap(parts){return '<div class="body-map-wrap"><div class="body-map-title">Orientační mapa karoserie</div><div class="body-map-placeholder"><strong>Mapa karoserie bude nahrazena přesným technickým obrysem vozidla.</strong><span>Současný chybný nákres byl odstraněn.</span></div><p class="muted small">Měření se zapisuje ke konkrétním karosářským dílům níže.</p></div>'}
function bodySection(){const parts=['Přední nárazník','Kapota','LP blatník','LP dveře','LZ dveře','Levý zadní bok','Víko kufru','Pravý zadní bok','PZ dveře','PP dveře','PP blatník','Pravý přední bok / dle karoserie','Zadní nárazník'];return card('body','3','Karoserie, světla, skla a lak','<div class="subhead"><b>3A · Vizuální stav karoserie, světel a skel</b><span>Světla zde pouze vizuálně – funkčnost patří do bodu 8.</span></div>'+point('body.visual','Karoserie – vizuální stav')+point('body.lights','Světla – pouze vizuální stav', '<p class="muted small">Praskliny, zamlžení, poškození, stav krytů a těles. Funkci světel zde nehodnotit.</p>')+point('body.glass','Skla – vizuální stav')+'<div class="subhead"><b>3B · Měření tloušťky laku</b><span>Zapisuje se nejvyšší naměřená hodnota, nikdy průměr.</span></div>'+bodyMap(parts)+'<div class="paint-grid">'+parts.map((p,i)=>'<div class="paint-part"><b>'+(i+1)+'. '+p+'</b><div class="paint-fields"><label>MAX µm<input data-field="paint.'+i+'.um" inputmode="numeric" placeholder="—"></label><label>Vyhodnocení<select data-field="paint.'+i+'.result"><option value="">Vyberte…</option><option>Původní / bez podezření</option><option>Lakováno</option><option>Podezření na větší opravu</option><option>PLAST</option><option>Nelze změřit</option></select></label></div>'+note('paint.'+i+'.note','Volitelné…')+media('paint.'+i+'.photos')+'</div>').join('')+'</div>')}

function wheels(){const ps=['LP','PP','LZ','PZ'];return card('wheels','4','Kola a pneumatiky','<p class="muted">Model pneumatiky ani rozměr/ET disku se rutinně nezapisují. Pneumatika a disk jsou samostatné kontrolní body. Fotografie slouží jako reálná dokumentace konkrétního kola.</p><div class="wheel-grid">'+ps.map(pos=>'<div class="wheel"><h3>'+pos+'</h3><div class="grid cols-3"><label>Rozměr pneumatiky<input data-field="wheels.'+pos+'.size" placeholder="215/55 R17"></label><label>DOT<input data-field="wheels.'+pos+'.dot" placeholder="2524"></label><label>Dezén mm<input data-field="wheels.'+pos+'.tread" inputmode="decimal" placeholder="5,4"></label></div>'+media('wheels.'+pos+'.overview','＋ Foto skutečného kola')+'<div class="component-block"><h4>Pneumatika</h4>'+status('wheels.'+pos+'.tire.status')+note('wheels.'+pos+'.tire.note','Pouze relevantní nález na pneumatice…')+media('wheels.'+pos+'.tire.photos')+'</div><div class="component-block"><h4>Disk</h4>'+status('wheels.'+pos+'.rim.status')+note('wheels.'+pos+'.rim.note','Poškození, deformace, prasklina, oprava / svar…')+media('wheels.'+pos+'.rim.photos')+'</div></div>').join('')+'</div>')}

function brakes(){const ps=['LP','PP','LZ','PZ'];return card('brakes','5','Brzdy','<p class="muted">Staticky hodnotíme pouze to, co je skutečně viditelné. Kotouč a destička jsou samostatné kontrolní body. Pokud destičku nelze spolehlivě vidět, použijte NEOVĚŘENO. Funkční chování brzd patří do zkušební jízdy.</p><div class="wheel-grid">'+ps.map(pos=>'<div class="wheel"><h3>'+pos+'</h3>'+media('brakes.'+pos+'.overview','＋ Foto skutečné brzdy')+'<div class="component-block"><h4>Brzdový kotouč</h4>'+status('brakes.'+pos+'.disc.status')+note('brakes.'+pos+'.disc.note','Nález na kotouči…')+media('brakes.'+pos+'.disc.photos')+'</div><div class="component-block"><h4>Brzdová destička</h4>'+status('brakes.'+pos+'.pad.status')+note('brakes.'+pos+'.pad.note','Nález na destičce…')+media('brakes.'+pos+'.pad.photos')+'</div><div class="component-block"><h4>Třmen – pouze viditelná abnormalita</h4>'+note('brakes.'+pos+'.caliper.note','Jen pokud je vidět koroze, poškození, únik nebo jiná abnormalita…')+media('brakes.'+pos+'.caliper.photos')+'</div></div>').join('')+'</div>'+point('brakes.fluid','Brzdová kapalina – hladina a vizuální stav') )}

function engine(){return card('engine','6','Motorový prostor, motor a převodovka','<div class="grid cols-2"><label>Teplota motoru při příjezdu<select data-field="engine.arrivalTemp"><option value="">Vyberte…</option><option>Studený</option><option>Částečně zahřátý</option><option>Zahřátý</option></select></label><label>Studený start<select data-field="engine.coldStart"><option value="">Vyberte…</option><option>Ověřen</option><option>Neověřen</option></select></label></div>'+point('engine.bay','Motorový prostor – vizuální stav')+point('engine.fluids','Provozní kapaliny – hladina a vizuální stav')+point('engine.battery','Akumulátor – vizuální stav / napětí pouze pokud změřeno')+point('engine.start','Start a chod motoru')+point('engine.warm','Kontrola po zahřátí')+point('engine.belts','Viditelné řemeny a příslušenství – pokud přístupné')+point('engine.gearboxVisual','Převodovka – pouze viditelný fyzický stav'))}

function underbody(){return card('underbody','7','Podvozek a nápravy','<label>Způsob kontroly<select data-field="underbody.method"><option value="">Vyberte…</option><option>Postupné přizvednutí jednotlivých částí vozidla pomocí mobilního zvedáku</option><option>Ze země / bez přizvednutí</option><option>Jiný způsob</option></select></label><p class="muted">Hodnotí se pouze skutečně viditelné a přístupné části bez demontáže. Skryté nebo nepřístupné části označte NEOVĚŘENO.</p>'+point('underbody.front','Přední náprava','<p class="muted small">Doporučené jsou alespoň 2 celkové dokumentační fotografie (levá/pravá strana). Přístupné prvky řízení lze uvést jako konkrétní nález zde; celou soustavu řízení staticky nehodnotíme.</p>')+point('underbody.rear','Zadní náprava','<p class="muted small">Doporučené jsou alespoň 2 celkové dokumentační fotografie (levá/pravá strana).</p>')+point('underbody.floor','Spodní část vozu / podlaha')+point('underbody.exhaust','Výfuková soustava')+point('underbody.drive','Pohon / 4×4 – viditelný fyzický stav')+point('underbody.special','Specifické systémy dle výbavy'))}

function interior(){const groups=[['info','Infotainment a konektivita'],['seats','Sedadla – funkčnost'],['lightsFunction','Osvětlení – funkčnost'],['cluster','Přístrojový štít a displeje'],['climate','Klimatizace, topení a ventilace'],['safety','Bezpečnostní a asistenční prvky'],['comfort','Ovládací a komfortní prvky']];return card('interior','8','Interiér a výbava','<div class="subhead"><b>8A · Vizuální stav interiéru</b></div>'+point('interior.visual','Interiér – vizuální stav')+'<div class="subhead"><b>8B · Funkčnost interiéru a výbavy</b><span>Hodnotí se přítomná výbava v širokých logických skupinách.</span></div>'+groups.map(([k,t])=>point('interior.'+k,t,'',false)).join(''))}

function documents(){return card('documents','9','Identifikace, dokumentace a servisní historie','<div class="subhead"><b>9A · Identifikace vozidla</b></div><div class="check-point"><h3>VIN a identifikátory</h3><p class="muted small">VIN se přebírá z bodu 1. V klientském reportu se automaticky nemaskuje; vložená fotografie zůstává v původní podobě.</p><label>Výsledek kontroly<select data-field="documents.identityResult"><option value="">Vyberte…</option><option>SOUHLASÍ</option><option>NESOULAD</option><option>NEOVĚŘENO</option></select></label>'+note('documents.identityNote','Poznámka pouze pokud je relevantní…')+media('documents.identityPhotos')+'</div><div class="subhead"><b>9B · Relevantní technické údaje a schválené změny</b></div>'+point('documents.tech','Relevantní technické údaje / registrované úpravy')+'<div class="subhead"><b>9C · Servisní historie a dokumentace</b></div><label>Stav doložení<select data-field="documents.history"><option value="">Vyberte…</option><option>Doložená</option><option>Částečně doložená</option><option>Nedoložená</option><option>Nebyla předložena</option></select></label>'+note('documents.historyNote','Stručné zhodnocení historie, např. pravidelnost, poslední doložený servis, chybějící důležitý doklad…')+media('documents.photos','＋ Přidat fotografie dokumentace')+'<label class="upload-box small"><input id="docsInput" type="file" multiple><strong>+ Přidat dokument / soubor</strong><span>Servisní kniha, faktury nebo jiné podklady</span></label><div id="docsList" class="photo-list"></div>')}

function diagnostics(){return card('diagnostics','10','Diagnostika','<label>Diagnostika provedena<select data-field="diagnostics.done"><option value="">Vyberte…</option><option>ANO</option><option>NE</option><option>NEBYLO MOŽNÉ PROVÉST</option></select></label>'+note('diagnostics.note','Vyhodnocení diagnostiky / komentář technika…')+media('diagnostics.photos','＋ Přidat foto')+'<label class="upload-box small"><input id="diagInput" type="file" multiple><strong>+ Přidat diagnostický protokol / soubor</strong><span>Více souborů; originální protokol zůstává přílohou klientského reportu</span></label><div id="diagList" class="photo-list"></div><div class="check-point"><h3>Významný diagnostický nález</h3><p class="muted small">Použijte pouze tehdy, když je konkrétní nález důležitý pro rozhodnutí o koupi.</p>'+status('diagnostics.significant.status')+note('diagnostics.significant.note','Konkrétní významný nález…')+'</div>')}

function drive(){const items=[['motor','Motor'],['gearbox','Převodovka / spojka'],['suspension','Podvozek'],['brakes','Brzdy + parkovací brzda'],['steering','Řízení'],['acceleration','Akcelerace'],['drivetrain','Pohon'],['assist','Asistenční systémy']];return card('drive','11','Zkušební jízda',items.map(([k,t])=>'<div class="check-point"><h3>'+t+'</h3>'+status('sections.drive.'+k+'.status')+note('sections.drive.'+k+'.note')+'</div>').join(''))}

function investments(){return card('investments','12','Doporučený servis a očekávané investice','<p class="muted">Přidávejte pouze položky, které sami považujete za doporučený servis nebo očekávanou investici. Částky zadává technik; systém je pouze sečte. Jde o orientační odhad, nikoli cenovou nabídku servisu.</p><div id="investmentRows"></div><button type="button" class="ghost" id="addInvestment">+ Přidat položku</button><div class="total-box"><span>OČEKÁVANÉ INVESTICE CELKEM</span><strong id="investmentTotal">0 – 0 Kč</strong></div>')}

function render(){nav();document.querySelector('#dynamicSections').innerHTML=[bodySection(),wheels(),brakes(),engine(),underbody(),interior(),documents(),diagnostics(),drive(),investments()].join('');renderInvestments();bind();restore();document.querySelector('#inspectionId').textContent=state.meta?.id||makeId();renderFiles();updateInvestmentTotal()}
function makeId(){const id='AR-'+new Date().getFullYear()+'-00001';set('meta.id',id);return id}
function bind(){document.querySelectorAll('[data-field]').forEach(el=>{const p=el.dataset.field;if(el.type==='checkbox'){el.checked=!!get(p);el.onchange=()=>set(p,el.checked)}else{el.value=get(p)??'';el.oninput=()=>set(p,el.value);el.onchange=()=>set(p,el.value)}});document.querySelectorAll('[data-choice] button').forEach(btn=>btn.onclick=()=>{const row=btn.closest('[data-choice]');set(row.dataset.choice,btn.dataset.value);row.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===btn))});document.querySelectorAll('[data-media]').forEach(inp=>inp.onchange=e=>{set(inp.dataset.media,[...e.target.files].map(f=>f.name));renderMedia()});document.querySelectorAll('.verdict-picker button').forEach(btn=>btn.onclick=()=>{set('final.verdict',btn.dataset.value);restore()});const add=document.querySelector('#addInvestment');if(add)add.onclick=()=>{const a=get('investments.items')||[];a.push({title:'',note:'',min:'',max:''});set('investments.items',a);renderInvestments();bind();restore()};const d=document.querySelector('#diagInput');if(d)d.onchange=e=>{set('diagnostics.files',[...e.target.files].map(f=>f.name));renderFiles()};const docs=document.querySelector('#docsInput');if(docs)docs.onchange=e=>{set('documents.files',[...e.target.files].map(f=>f.name));renderFiles()};renderMedia()}
function restore(){document.querySelectorAll('[data-choice]').forEach(row=>{const v=get(row.dataset.choice);row.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.value===v))});const v=get('final.verdict');document.querySelectorAll('.verdict-picker button').forEach(b=>b.classList.toggle('active',b.dataset.value===v))}
function renderMedia(){document.querySelectorAll('[data-media-list]').forEach(el=>{const a=get(el.dataset.mediaList)||[];el.innerHTML=a.map(n=>'<span class="photo-pill">'+esc(n)+'</span>').join('')})}
function renderInvestments(){const el=document.querySelector('#investmentRows');if(!el)return;const a=get('investments.items')||[];el.innerHTML=a.map((x,i)=>'<div class="investment-row"><label>Nález / doporučený servis<input data-field="investments.items.'+i+'.title" placeholder="Např. přední brzdové kotouče + destičky"></label>'+note('investments.items.'+i+'.note','Doporučení / stručný komentář…')+'<div class="grid cols-2"><label>Od Kč<input data-field="investments.items.'+i+'.min" inputmode="numeric"></label><label>Do Kč<input data-field="investments.items.'+i+'.max" inputmode="numeric"></label></div><button type="button" class="remove-investment" data-i="'+i+'">Odstranit</button></div>').join('');el.querySelectorAll('.remove-investment').forEach(b=>b.onclick=()=>{const a=get('investments.items')||[];a.splice(+b.dataset.i,1);set('investments.items',a);renderInvestments();bind();restore()});updateInvestmentTotal()}
function money(v){return Number(String(v||'').replace(/\D/g,''))||0}
function updateInvestmentTotal(){const a=get('investments.items')||[];let min=0,max=0;a.forEach(x=>{min+=money(x.min);max+=money(x.max)});const txt=min.toLocaleString('cs-CZ')+' – '+max.toLocaleString('cs-CZ')+' Kč';const e=document.querySelector('#investmentTotal');if(e)e.textContent=txt;const f=document.querySelector('#finalInvestmentTotal');if(f)f.textContent=txt}
function renderFiles(){const p=document.querySelector('#photoList');if(p)p.innerHTML=(get('photos.names')||[]).map(n=>'<span class="photo-pill">'+esc(n)+'</span>').join('');const d=document.querySelector('#diagList');if(d)d.innerHTML=(get('diagnostics.files')||[]).map(n=>'<span class="photo-pill">'+esc(n)+'</span>').join('');const docs=document.querySelector('#docsList');if(docs)docs.innerHTML=(get('documents.files')||[]).map(n=>'<span class="photo-pill">'+esc(n)+'</span>').join('')}
function validate(){const missing=[];[['vehicle.make','Značka vozidla'],['vehicle.model','Model vozidla'],['vehicle.vin','VIN'],['vehicle.mileage','Stav km'],['final.verdict','Finální rozsudek'],['final.summary','Celkové hodnocení technika']].forEach(([p,n])=>{if(!get(p))missing.push(n)});const el=document.querySelector('#validationResult');if(!el)return;if(missing.length){el.innerHTML='<div class="validation warnbox"><strong>Před vytvořením reportu zkontrolujte:</strong><ul>'+missing.map(x=>'<li>'+x+'</li>').join('')+'</ul><span>NEOVĚŘENO a NERELEVANTNÍ se nepovažují za chybu.</span></div>'}else{el.innerHTML='<div class="validation okbox"><strong>Základní kontrola je kompletní.</strong><span>V produkční verzi by nyní následovalo vytvoření klientského reportu.</span></div>'}}
document.querySelector('#photoInput').onchange=e=>{set('photos.names',[...e.target.files].map(f=>f.name));renderFiles()};
document.querySelector('#resetBtn').onclick=()=>{if(confirm('Opravdu vymazat celý lokálně uložený koncept této kontroly?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
document.querySelector('#reportBtn').onclick=validate;
render();